
questions:
  - &cluster_name
    identifier: cluster_name
    question: 'Name of the cluster'

  - &domain
    identifier: domain
    question: 'Fully-qualified domain name for cluster nodes'
    default: '<%= domain.config.cluster %>.alces.network'

  - &cloudware_domain
    identifier: cloudware_domain
    question: 'Subnet of cloudware domain0'
    default: '10.78.0.0'

  - &clusters_network
    identifier: clusters_network
    question: 'Subnet of cloudware clusters'
    default: '10.100.0.0'

  - &externaldns
    identifier: externaldns
    question: 'External DNS server IP'

  - &internaldns
    identifier: internaldns
    question: "Internal DNS server IP (usually the gateway's primary IP)"

  - &root_password
    identifier: root_password
    question: 'Root user encrypted password'

  - &root_ssh_key
    identifier: root_ssh_key
    question: 'Root user SSH key'

  - &dns_type
    identifier: dns_type
    question: 'DNS type to use for cluster'
    default: 'hosts'
    choices:
      - 'hosts'
      - 'named'

  - &genders_host_range
    identifier: genders_host_range
    question: "Genders host range specifier for this group, e.g. 'node01,node[05-08]'"

  - &genders_host_role
    identifier: genders_host_role
    question: 'What are the roles of machines in the group?'
    default: 'compute'
    choices:
      - 'compute'
      - 'service'

  - &genders_all_group
    identifier: genders_all_group
    question: 'Include these nodes in the `all` group?'
    type: 'boolean'

  - &genders_additional_groups
    identifier: genders_additional_groups
    question: "Additional genders groups for this group, e.g. 'storage,rack1'; the group being configured is the primary group"
    default: ''

  - &kickstart_template
    identifier: kickstart_template
    question: 'Kickstart template to use'
    default: 'default'

  - &pxelinux_template
    identifier: pxelinux_template
    question: 'PXELINUX template to use'
    default: 'default'

  - &postfix_relay
    identifier: postfix_relay
    question: 'Postfix relay server for mail (usually the gateway)'
    default: 'gateway.<%= config.networks.pri.domain %>.<%= config.domain %>'

  # Primary network.
  - &pri_network_defined
    identifier: pri_network_defined
    question: 'Setup primary network?'
    type: 'boolean'

  - &pri_network_domain
    identifier: pri_network_domain
    question: 'Domain for the primary network (usually the cloudware domain name)'
    default: 'pri'

  - &pri_network_ip
    identifier: pri_network_ip
    question: 'IP for nodes on the primary network'
    default: '10.100.<%= node.group.index %>.<%= node.index %>'

  - &pri_network_ip_node
    identifier: pri_network_ip_node
    question: 'IP address for the node (primary network)'

  - &pri_network_netmask
    identifier: pri_network_netmask
    question: 'Netmask for the primary network'
    default: '255.255.0.0'

  - &pri_network_network
    identifier: pri_network_network
    question: 'Network IP for the primary network'
    default: '10.100.<%= node.group.index %>.0'

  - &pri_network_gateway
    identifier: pri_network_gateway
    question: "Gateway IP for the primary network (usually login1's primary IP)"
    default: '10.100.<%= node.group.index %>.10'

  - &pri_network_interface
    identifier: pri_network_interface
    question: 'Interface for the primary network'
    default: 'eth0'

  - &pri_network_short_hostname
    identifier: pri_network_short_hostname
    question: 'Hostname for node PRI'
    default: 'gateway.<%= config.networks.pri.domain %>'

domain:
  - *cluster_name
  - *root_password
  - *root_ssh_key
  - *dns_type

group:
  - *genders_host_range
  - *genders_host_role
  - *genders_all_group
  - *genders_additional_groups

  - *pri_network_ip
  - *pri_network_domain
  - *pri_network_network
  - *pri_network_gateway

node:
  - *pri_network_ip_node
  - *pri_network_gateway
  - *pri_network_interface

local:
  - *pri_network_short_hostname
