networks:
  pri:
    ip: 10.10.0.<%= node.index + 55 %>
is_vm: <%= answer.is_vm %>
libvirt_host: <%= answer.libvirt_host %>
vm_disk_pool: <%= answer.vm_disk_pool %>
vm_root_disk_size: <%= answer.vm_root_disk_size %>
vm_disk_pool_path: <%= answer.vm_disk_pool_path %>
vm_memory: <%= answer.vm_memory %>
vm_cpus: <%= answer.vm_cpus %>
vm_mac_address_build: <%= answer.vm_mac_address_build %>
disksetup: |
  zerombr
  bootloader --location=mbr --driveorder=<%= config.disklabel %> --append="$bootloaderappend"
  clearpart --all --initlabel

  #Disk partitioning information
  part /boot --fstype ext4 --size=4096 --asprimary --ondisk <%= config.disklabel %>
  part pv.01 --size=1 --grow --asprimary --ondisk <%= config.disklabel %>
  volgroup system pv.01
  logvol  /  --fstype ext4 --vgname=system  --size=16384 --name=root
  logvol  /var --fstype ext4 --vgname=system --size=4096 --name=var
  logvol  /tmp --fstype ext4 --vgname=system --size=1 --name=tmp --grow
  logvol  swap  --fstype swap --vgname=system  --size=8096  --name=swap1
