networks:
  pri:
    ip: 10.10.0.<%= node.index + 55 %>
  mgt:
    defined: false
  ib:
    defined: false
  bmc:
    defined: false
is_vm: true
libvirt_host: 'master1'
vm_disk_pool: 'local'
vm_root_disk_size: 80
vm_disk_pool_path: '/opt/vm'
vm_memory: 4
vm_cpus: 2
vm_mac_address_build: '00:<%= (1..5).map{"%0.2X"%rand(256)}.join(":") %>'
disksetup: |
  zerombr
  bootloader --location=mbr --driveorder=<%= config.disklabel %> --append="$bootloaderappend"
  clearpart --all --initlabel

  #Disk partitioning information
  part /boot --fstype ext4 --size=4096 --asprimary --ondisk <%= config.disklabel %>
  part pv.01 --size=1 --grow --asprimary --ondisk <%= config.disklabel %>
  volgroup system pv.01
  logvol  /  --fstype ext4 --vgname=system  --size=16384 --name=root
  logvol  /var --fstype ext4 --vgname=system --size=16384 --name=var --grow
  logvol  /tmp --fstype ext4 --vgname=system --size=1 --name=tmp
  logvol  swap  --fstype swap --vgname=system  --size=8096  --name=swap1
